# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Declarant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!



  # Pods for Declarant

pod 'Alamofire', '~> 4.6'



  target 'DeclarantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeclarantUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
